export const toures = [
  {
    country: "Турция",
    city: "Анталия",
    date: "19.03.21 - 25.03.21",
    duration: "6 ночей",
    from: "Бишкек",
    currency: "USD",
    cost: "400",
    title: "Наследие турции",
    img: "https://kochevnik.kg/wp-content/uploads/2020/01/Anya-Dryagina-Efes-IMG_8492-25-1024x684.jpg",
    content: [
      "Авиаперелёт Алматы — Пхукет — Алматы",
      "Проживание в отеле",
      "Питание на базе завтрака",
      "Трансфер аэропорт – отель – аэропорт",
    ],
  },
  {
    country: "Турция",
    city: "Стамбул",
    date: "23.03.20 - 30.03.20",
    duration: "7 ночей",
    currency: "EUR",
    from: "Бишкек",
    cost: "345",
    title: "Золотое кольцо Турции",
    img: "https://kochevnik.kg/wp-content/uploads/2019/08/3-1-1024x621.jpg",
    content: [
      "Авиаперелёт Алматы — Пхукет — Алматы",
      "Проживание в отеле",
      "Питание на базе завтрака",
      "Трансфер аэропорт – отель – аэропорт",
    ],
  },
  {
    country: "Таиланд",
    city: "Пхукет",
    date: "20.03.20 - 30.03.20",
    duration: "10 ночей",
    from: "Алматы",
    cost: "812",
    currency: "USD",
    title: "ПХУКЕТ | THE NATURE PHUKET 5*",
    img: "https://kochevnik.kg/wp-content/uploads/2020/02/225701578.jpg",
    content: [
      "Авиаперелёт Алматы — Пхукет — Алматы",
      "Проживание в отеле",
      "Питание на базе завтрака",
      "Трансфер аэропорт – отель – аэропорт",
    ],
  },
  {
    country: "Таиланд",
    city: "Пхукет",
    date: "20.03.20 - 30.03.20",
    duration: "10 ночей",
    from: "Алматы",
    cost: "661",
    currency: "EUR",
    title: "ПХУКЕТ | PGS HOTELS CASADEL SOL 4*",
    img: "https://kochevnik.kg/wp-content/uploads/2020/03/original_78571665.jpg",
    content: [
      "Авиаперелёт Алматы — Пхукет — Алматы",
      "Проживание в отеле",
      "Питание на базе завтрака",
      "Трансфер аэропорт – отель – аэропорт",
    ],
  },
  {
    country: "Турция",
    city: "Анталия",
    date: "20.03.20 - 30.03.20",
    duration: "10 ночей",
    from: "Алматы",
    cost: "690",
    currency: "USD",
    title: "Майские праздники в Солнечной Анталье",
    img: "https://kochevnik.kg/wp-content/uploads/2020/03/d7c1b4f233d81605743409d5e1a69065fe2d010308a6b3799a3d9c728ee74244-1024x768.png",
    content: [
      "Авиаперелёт Алматы — Анталия",
      "Проживание в отеле",
      "Питание на базе завтрака",
      "Трансфер аэропорт – отель – аэропорт",
    ],
  },
  {
    country: "Таиланд",
    city: "Пхукет",
    date: "20.03.20 - 30.03.20",
    duration: "10 ночей",
    from: "Алматы",
    cost: "758",
    currency: "EUR",
    title: "Пхукет | Dream Phuket Hotel Laguna 5*",
    img: "https://kochevnik.kg/wp-content/uploads/2020/02/117680370.jpg",
    content: [
      "Авиаперелёт Алматы — Анталия",
      "Проживание в отеле",
      "Питание на базе завтрака",
      "Трансфер аэропорт – отель – аэропорт",
    ],
  },
];
